### ISSUE TITLE
RADV: Had to recompile all the shaders anyway

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [GolDNenex/overwatch2-dxvk-cache#1]
All the dxvk caches that I have found online are completely useless on my AMD card (im using mesa-git), I end up having to compile everything anyway. (same story for this one) I just wanted to let you know in case this was actually a you problem and not a me problem.

**Comment by GolDNenex** [comment]
Shaders compile at launch for everyone, no matter where your GPU comes from.

The dxvk-cache file, isn't a cache file per say. This file contain the "translation" between directx and vulkan. At launch this just give at dxvk where are the shaders to compile and dxvk compile them. The more dxvk-cache is filled, the less you risk to encounter shader that need to be compile in game (this will give you stutters).

**Comment by Etaash-mathamsetty** [comment]
> Shaders compile at launch for everyone, no matter where your GPU comes from.
> 
> The dxvk-cache file, isn't a cache file per say. This file contain the "translation" between directx and vulkan. At launch this just give at dxvk where are the shaders to compile and dxvk compile them. The more dxvk-cache is filled, the less you risk to encounter shader that need to be compile in game (this will give you stutters).

that doesn't explain why I had to wait over 15 minutes to compile everything all over again

**Comment by GolDNenex** [comment]
Not sure what you don't understand. Its how it is for everyone. Maybe someday the dxvk team will be able to fix it but for now nobody know if something can be done at all.

I'm not a dxvk developer and i can't help you more than explaining you how its work in this use-case.

I don't know your hardware but its more shorter for me (~3/5min).
